name: Data Schema Code Convention

on:
  push:
    branches: [LW11]

jobs:
  data_schema_linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install and Run SQLFluff
        run: |
          pip install sqlfluff
          sqlfluff lint $GITHUB_WORKSPACE/DataSchema.sql --dialect oracle
